runtime: go122

env_variables:
  PORT: 8080
  GOOGLE_APPLICATION_CREDENTIALS: serviceAccountKey.json

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10